### ISSUE TITLE
Extra kernels are broken on demo

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jyve#35]
Seems like all the vendor bundles aren't resolve, though are clearly in gh-pages. Might be temporary?

**Comment by bollwyvl** [comment]
K, looks like it's trying to access:
```
https://deathbeds.github.io/lab/static/vendors~brython.573bac019ecde4ea1fc5.js
```
but 
```
https://deathbeds.github.io/jyve/lab/static/vendors~brython.573bac019ecde4ea1fc5.js
```

is the thing. Must be messing up some config paths. Should generate/test with an alternate prefix... probably with https...

**Comment by SimonBiggs** [comment]
Some config works on mine using a the CNAME of jyve.simonbiggs.net

Maybe it's an issue with base url or something like that?
