### ISSUE TITLE
Support package repositories

### ISSUE THREAD

**Issue by westurner** [deathbeds/jyve#46]
Users can securely "install" packages from remote package repositories.
- To disk (See: #47 Save to disk with Native File System API)
- To browser storage?

*****

Would miniforge and conda-forge build a WASM architecture target? They've added an aarch64 build target.
Should packages be built with Emscripten or WASI?
How does pyodide build packages?
Is there a way to specify package hashes with `import`/`require()` statements; just like Subresource Integrity cryptographic hashes? https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by westurner** [comment]
> *Emscripten or WASI?*

See: https://github.com/termux/termux-app/issues/1072#issuecomment-633647205 re: WASI/Emscripten

**Comment by tonyfast** [comment]
this out of context to the project. 

maybe writing some code would help us.

PRs accepted though if you want to contribute some code sometime.

**Comment by westurner** [comment]
This is disrespectful behavior (#46, #47) and it turns away potential project contributors.

Writing code is not necessary to promote discussion about potential new features which - in this case - will require new features in a module loader.

**Comment by westurner** [comment]
Do you or this organization have a Code of Conduct?

**Comment by tonyfast** [comment]
> This is disrespectful behavior (#46, #47) and it turns away potential project contributors.

🤷🏻. we're happy to accept contributors.

we don't have a code of conduct. i'm not sure why we need one.

**Comment by westurner** [comment]
This is a surefire way to turn away developers who might otherwise have time, code, money, and ideas:

> maybe writing some code would help us.
>
> PRs accepted though if you want to contribute some code sometime.

A Code of Conduct could clarify that you welcome new ideas and security suggestions.

> this out of context to the project.

Is pyodide going to implement a new module loader that checks hashes? https://github.com/iodide-project/pyodide/issues/738

Maybe this is not in scope for this project but you would welcome implementation in requisite components and you recognize the security risk of loading untrusted modules (using JS code that I now don't care to share with due to being disrespectfully called spam and turned away in #47).

Is this a feature that may be implemented in a component this application depends upon which will likely need at least future configuration in order for this user story to be true for this application?

**Comment by tonyfast** [comment]
Not all open source projects are created the same. This is our "for fun" work. This project is an idea.

There haven't been commits made in a long time. Jyve is on a Jupyter 1.0 branch. Pyiodide versions are old as f. These topics are out scope.

You're clearly full of information that might bring us value. Deathbeds is here for fun and conversation. Bring some of that and we'll play.
