### ISSUE TITLE
Save to disk with Native File System API

### ISSUE THREAD

**Issue by westurner** [deathbeds/jyve#47]
Users can read and write to disk with the Native File System API
https://web.dev/native-file-system/

> The Native File System API (formerly known as the Writeable Files API) enables developers to build powerful web apps that interact with files on the user's local device, like IDEs, photo and video editors, text editors, and more. After a user grants a web app access, this API allows web apps to read or save changes directly to files and folders on the user's device. Beyond reading and writing files, the Native File System API provides the ability to open a directory and enumerate its contents.

https://github.com/wicg/native-file-system/issues/

**Comment by tonyfast** [comment]
what are we supposed to do with this. closing as spam.

**Comment by westurner** [comment]
@tonyfast 
> what are we supposed to do with this. closing as spam.

This is a potential feature. This software application could save notebooks to disk from the browser using this new standard.

> Users can read and write to disk with the The Native File System API

This is a User Story. If this feature is sufficiently implemented, this user story would be true.
