### ISSUE TITLE
JupyterLab 3.0 Support

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jyve#48]
## Elevator Pitch

Demonstrate JupyterLab 3.0 support shortly around initial release.

## Benefits
- no nodejs/webpack/npm needed to install new packages
- pure pip/conda-distributable build times
- first-party support of `worker-loader`
- improved workspace support
- improved single-document mode may be good for offline jyve builds

## Resources
- enough of the stack is ready to start basic testing, e.g. [binder](https://gist.github.com/bollwyvl/3e82c0c2c15dae0683e80f2620039111)
- workspaces might provide some new and interesting opportunities

## Risks
- implementation
  - front-end
    - kernels will have changed again, even beyond the unfinished work on #44 
  - backend
    - significant nbconvert changes have landed
    - jupyter_server needs to be accounted for
- testing
  - robot
    - command palette has changed (two menu clicks, or a three-key chord)
- upstream
  - robotframework-jupyterlibrary needs significant overhaul

## Related
- supersedes #44
  - there will be no point in supporting jupyterlab 1/2 in light of the above benefits

**Comment by bollwyvl** [comment]
maybe consider abandoning jyve, contribute to more recent:

https://github.com/jtpio/jupyterlite

**Comment by SimonBiggs** [comment]
Wow, that is amazing.

**Comment by bollwyvl** [comment]
Yep, jyve is dead, long live lite.

**Comment by SimonBiggs** [comment]
Long live lite :slightly_smiling_face: :tada:
